# -------- BUILD --------
    FROM oven/bun:1-alpine AS build

    WORKDIR /app
    
    COPY . .
    
    RUN bun install
    RUN bun run build
    
    # -------- PRODUCTION --------
    FROM nginx:stable-alpine
    
    RUN rm -rf /usr/share/nginx/html/*
    
    COPY --from=build /app/dist/booksmart_pwa/browser/ /usr/share/nginx/html
    
    COPY nginx.conf /etc/nginx/conf.d/default.conf
    
    EXPOSE 80
    
    CMD ["nginx", "-g", "daemon off;"]
    